export enum PokeType {
  Bug,
  Dark,
  Dragon,
  Electric,
  Fairy,
  Fighting,
  Fire,
  Flying,
  Ghost,
  Grass,
  Ground,
  Ice,
  Normal,
  Poison,
  Psychic,
  Rock,
  Steel,
  Water,
};

export interface PokeConfig {
  pIndex: number;
  name: string;
  img: string;
  type: [PokeType, PokeType?],
}

/** TODO finalize */
export const POKEMONS: PokeConfig[] = [
  {
    pIndex: 1,
    name: 'Bulbasaur',
    img: '1',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
  {
    pIndex: 2,
    name: 'Ivysaur',
    img: '2',
    type: [PokeType.Grass, PokeType.Poison],
  },
];
